# Generated by Django 5.1.6 on 2025-03-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippngaddress',
            options={'verbose_name_plural': 'shipping Address'},
        ),
        migrations.RemoveField(
            model_name='shippngaddress',
            name='shipping_old_cart',
        ),
    ]
