# Generated by Django 5.1.6 on 2025-03-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippngaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippngaddress',
            name='shipping_address1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shippngaddress',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shippngaddress',
            name='shipping_city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shippngaddress',
            name='shipping_phone',
            field=models.CharField(max_length=25),
        ),
    ]
