# Generated by Django 5.1.6 on 2025-03-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0020_alter_order_date'),
        ('payment', '0003_alter_shippngaddress_shipping_address1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippngaddress',
            name='shipping_address1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shippngaddress',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='shippngaddress',
            name='shipping_email',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='shippngaddress',
            name='shipping_full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='shippngaddress',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('shipping_address', models.TextField(max_length=150000)),
                ('amount_paid', models.IntegerField(default=0)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
