# Generated by Django 5.1.6 on 2025-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shippngaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sttus',
            field=models.CharField(choices=[('Pending', 'Waiting for paying'), ('Processing', 'Processing'), ('Shipped', 'Sended to Post'), ('Delivered', 'it has delivered')], default='Pending', max_length=50),
        ),
    ]
