# Generated by Django 5.1.6 on 2025-03-30 14:08

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_sttus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sttus',
            new_name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='last_update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
