# Generated by Django 5.1.6 on 2025-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_sttus_order_status_order_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Waiting for Paying'), ('Processing', 'Processing'), ('Shipped', 'Sended to Post'), ('Delivered', 'It has delivered')], default='Pending', max_length=50),
        ),
    ]
