# Generated by Django 5.1.6 on 2025-03-05 19:24

import datetime
import django.db.models.deletion
import mall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('number', models.CharField(help_text='شماره را با 09 وارد کنید', max_length=20)),
                ('email', models.EmailField(max_length=110)),
                ('passwoed', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('price', models.IntegerField(default=0, max_length=12)),
                ('image', models.ImageField(upload_to='upload/product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, max_length=50)),
                ('address', models.CharField(blank=True, default='')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(default=datetime.datetime(2025, 3, 5, 22, 54, 14, 345625))),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.product')),
            ],
        ),
    ]
