# Generated by Django 5.1.6 on 2025-03-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_alter_order_date_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 6, 16, 34, 56, 992235)),
        ),
    ]
