# Generated by Django 5.1.6 on 2025-03-11 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_remove_product_image_product_extra_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 11, 17, 55, 12, 775115)),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='Lorem ipsum odor amet, consectetuer adipiscing elit. Risus malesuada erat venenatis sed suspendisse dictum. Ullamcorper placerat aliquam sit rhoncus; class blandit varius. Primis diam aptent mus maecenas inceptos quam.', max_length=500, null=True),
        ),
    ]
