# Generated by Django 5.1.6 on 2025-03-11 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 11, 18, 59, 59, 121524)),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('M', 32), ('L', 42), ('XL', 52)], max_length=4, null=True),
        ),
    ]
