# Generated by Django 5.1.6 on 2025-03-25 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0016_alter_order_date_alter_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 23, 48, 39, 787404)),
        ),
    ]
