# Generated by Django 5.1.6 on 2025-03-26 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0018_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 26, 12, 19, 3, 951903)),
        ),
    ]
