# Generated by Django 5.1.6 on 2025-03-30 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0023_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 30, 18, 46, 25, 917820)),
        ),
    ]
