# Generated by Django 5.1.6 on 2025-03-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0024_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
