# Generated by Django 5.1.6 on 2025-04-02 19:06

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User=get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin','zanafani6595@gmail.com','zana.1387')

class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0026_profile_full_name'),
    ]

    operations = [
        migrations.RunPython(create_superuser),

    ]
