# Generated by Django 5.1.6 on 2025-06-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0027_auto_20250402_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
